// CSV/Excel Export Utility

interface ViolationData {
  _id: string;
  vehicleNumber: string;
  detectionTimestamp: string;
  location: {
    address: string;
  };
  beamIntensity: number;
  fineAmount: number;
  status: string;
  aiConfidence: number;
  cameraId: string;
}

export function exportToCSV(violations: ViolationData[], filename?: string): void {
  // Define CSV headers
  const headers = [
    'Challan ID',
    'Vehicle Number',
    'Date & Time',
    'Location',
    'Beam Intensity (%)',
    'Fine Amount (₹)',
    'Status',
    'AI Confidence (%)',
    'Camera ID',
  ];

  // Convert data to CSV rows
  const rows = violations.map((v) => [
    `HB-${v._id.slice(-8).toUpperCase()}`,
    v.vehicleNumber,
    new Date(v.detectionTimestamp).toLocaleString('en-IN'),
    `"${v.location.address.replace(/"/g, '""')}"`, // Escape quotes in address
    v.beamIntensity.toString(),
    v.fineAmount.toString(),
    v.status.toUpperCase(),
    (v.aiConfidence * 100).toFixed(1),
    v.cameraId,
  ]);

  // Combine headers and rows
  const csvContent = [
    headers.join(','),
    ...rows.map((row) => row.join(',')),
  ].join('\n');

  // Add BOM for Excel UTF-8 compatibility
  const BOM = '\uFEFF';
  const blob = new Blob([BOM + csvContent], { type: 'text/csv;charset=utf-8;' });

  // Generate filename with date
  const date = new Date().toISOString().split('T')[0];
  const downloadFilename = filename || `violations_${date}.csv`;

  // Trigger download
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  link.setAttribute('href', url);
  link.setAttribute('download', downloadFilename);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

// Export summary statistics
export function exportSummaryCSV(stats: {
  totalViolations: number;
  pendingApproval: number;
  approved: number;
  totalRevenue: number;
  dateRange?: { from: string; to: string };
}): void {
  const date = new Date().toISOString().split('T')[0];
  
  const content = `
High Beam Detection System - Summary Report
Generated: ${new Date().toLocaleString('en-IN')}
${stats.dateRange ? `Period: ${stats.dateRange.from} to ${stats.dateRange.to}` : ''}

SUMMARY STATISTICS
==================
Total Violations,${stats.totalViolations}
Pending Approval,${stats.pendingApproval}
Approved,${stats.approved}
Total Revenue (₹),${stats.totalRevenue}

---
Report generated by AI High Beam Detection System
  `.trim();

  const BOM = '\uFEFF';
  const blob = new Blob([BOM + content], { type: 'text/csv;charset=utf-8;' });
  
  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob);
  link.download = `summary_report_${date}.csv`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}
